### ISSUE TITLE
Automatic non-generic names?

### ISSUE THREAD

**Issue by tschoppi** [tschoppi/starsystem-gen#21]
Maybe it would be cool to have all the bodies in the systems named, possibly using a Markov chain. The problems would be that there needs to be some kind of seed for the names. Maybe Tolkien elvish or something like that might do well, but we could also try English. It should be memory light, so no saving of all the words in memory. We'll have to figure something out...

**Comment by MyrionPhoenixmoon** [comment]
You could generate them based on a sort of classification system.
Type of Star - Type of Planet - Has Moons - Has Water - Habitable? - Number in System

Alternatively:
Have various "themed" Lists prepared, like place names from various real-world cultures, pantheons, scientific concepts or even fiction.
That way you don't get the all-nonsense starsystem names *and* at the same time you generate a hook about the background of the system. Was it found by a fan of Battlestar Galactica? Did the Mayans go to space? Did they *come* from here??

**Comment by MyrionPhoenixmoon** [comment]
In the case of pre-generated names, what happens when we run out of names?

Is there a maximum amount of names we need, and then require all lists to be at least that long?
Don't think this is the way to go, in case we decide e.g. moons get names too, or the number changes for any other reason.

Have some sort of algorithm for reusing names with a suffix? E.g. Luna Secundus, Hera Beta?
Difficult, but could be awesome. Reuse without suffix seems silly.

**Comment by MyrionPhoenixmoon** [comment]
I have currently implemented the reuse scenario with a single set of suffixes. I'm going to leave it at that for now and focus on random-generated names.

**Comment by MyrionPhoenixmoon** [comment]
Commit 0d7e9c9 implemented a basic markov chain with depth 1.
It can not be used with the simple naming scheme, as no corpus is loaded then, and the names are not yet very similar to the input, since the depth is too low for that, but it works.
