### ISSUE TITLE
Orbit visualizations

### ISSUE THREAD

**Issue by MyrionPhoenixmoon** [tschoppi/starsystem-gen#24]
The orbits, particularly the eccentricities are hard to visualize purely with numbers.
Ideally, there would be overview graphics for the star systems.

**Comment by tschoppi** [comment]
I like the idea. 

A problem presented by the nature of the logarithmic scaling of the orbits is that if you show all orbits, the inner orbits are all far too close to each other to discern properly. Maybe an "inner" and "greater" view are required for higher clarity.

Also, the rulebook leaves out two more variables that are needed for describing the orbit completely; The argument of periapsis (where is the pointy bit of the ellipsis) and the inclination towards the reference plane of the planet system. Inclination can be assumed to be very small, as the planets all form from the same stellar dust plate. The argument of periapsis (or perihelion) is probably [randomly distributed](http://astronomy.stackexchange.com/questions/6046/is-the-argument-of-perihelion-random), so that one's pretty easy as well. Methods for generating these values would have to be added in order to properly and completely describe the orbits.

**Comment by MyrionPhoenixmoon** [comment]
I have implemented an orbital visualization, using a random argument of periapsis (stored in a cookie, so that the values don't change when reloading the page) and a 2D view, so that the inclination of towards the plane doesn't matter.
The diagram currently depicts a planetary system, rather then an entire star system.

It seems that there little problem with distinguishing the inner orbits, but the star is tiny (1px radius).
If I make the star bigger, the orbits need to be accordingly bigger, leading to unusably huge images.

Current state:
![image](https://cloud.githubusercontent.com/assets/1800739/9848948/43197a7e-5ae6-11e5-8af0-fba8e31f813c.png)

**Comment by tschoppi** [comment]
Looks good! Some kind of labelling system and different colors (maybe also different line types?) for different kinds of worlds will hopefully augment the "take-it-all-in-with-one-glance" effect we're shooting for here.

**Comment by MyrionPhoenixmoon** [comment]
Labelling is certainly going to happen :)

Line types or colors might be an idea. Ideally I want to have objects represented by an icon somewhere on the orbit, however.

**Comment by MyrionPhoenixmoon** [comment]
Labels have happened.
Usually they look good:
![image](https://cloud.githubusercontent.com/assets/1800739/9862189/82aa872c-5b37-11e5-98af-ae8cab3b541c.png)

Sometimes, they don't...
![image](https://cloud.githubusercontent.com/assets/1800739/9862205/9e0228b8-5b37-11e5-9214-defdfc474585.png)

Ideas for fixing that would be appreciated.
Otherwise I'll call labeling and planet icons okay for now.

**Comment by tschoppi** [comment]
As I haven't reviewed the code you use for the labels yet, my only idea of fixing ugly clipping of the labels is to add white glow (or "shadow") around the text. That way the labels retain legibility with minimal disturbance of the orbit lines.

**Comment by MyrionPhoenixmoon** [comment]
Nice idea, but canvas treats text as paths, so there is no simple *background color* or similar method available.
I can fake a background rectangle, but since I draw the labels at the same time as the ellipses, later ellipses draw right over the labels.

Which tells me that I should really restructure the code to remember the ellipses and draw the labels in a separate function. Then I could possibly also check the labels for overlap...

**Comment by tschoppi** [comment]
As it currently stands, this issue has been resolved with commit c63aa503e23929ab3a3fb31e86b412d32033f62b, further adjustments (or rewritings-from-scratch) will be coordinated via new issues.
